import os

def read_xml_to_text(input_directory, output_file):
    with open(output_file, 'w') as outfile:
        for filename in os.listdir(input_directory):
            if filename.endswith('.xml'):
                filepath = os.path.join(input_directory, filename)
                with open(filepath, 'r') as file:
                    for line in file:
                        outfile.write(line)

# Path to the directory containing XML files generated by Maven Surefire
xml_directory = 'target/surefire-reports'
# Output text file where the XML contents will be written
output_text_file = 'test_report.txt'

read_xml_to_text(xml_directory, output_text_file)